"""Twin experiment on the Lorenz (1963) system.

The truth is generated by integrating the model itself (optionally with a
manual model bias on the observations), observations are sampled from the
noisy truth, and an ensemble with perturbed initial state and parameters is
filtered with a bias-blind (EnKF/EnSRKF) or bias-aware (rBA-EnKF + ESN)
method. The whole experiment is described by ``configs/twin_da/lorenz63.yml``
and runs through `romda.experiments.physical` — the same flow as

    python -m romda.experiments configs/twin_da/lorenz63.yml [--seed N] [--set da.m=32]

Run as a script for the default experiment plus figures, or import
`run_experiment` from the ablation studies in ``scripts/ablations``.
"""

import numpy as np
from common import load_main_config, parse_main_args, print_metrics, show_or_save_figs
from romda import experiments as physical
from romda.models.physical import Lorenz63

CFG = load_main_config('twin_da/lorenz63')


def manual_bias(name):
    """The study's historical bias shapes (NOT the `Observations` built-ins:
    its 'linear' is ``.1 max + .3 y``, this one ``.3 max + .3 y``)."""
    if name is None or name == 'nobias':
        return None
    if name == 'linear':
        return lambda yy, tt: (.3 * np.max(yy, axis=0) + .3 * yy, 'linear')
    if name == 'nonlinear':
        return lambda yy, tt: (.3 * np.max(yy, axis=0) *
                               (np.cos((yy / np.max(yy, axis=0)) ** 2) + 1), 'nonlinear')
    raise ValueError(f'Unknown manual bias {name}')


def run_experiment(**kwargs):
    """`romda.experiments.physical.run_experiment` on the lorenz63 config; accepts
    the same overrides (`da_method`, `std_obs`, `truth_kwargs`, `ensemble_kwargs`,
    `bias_kwargs`, `t_extra`, `seed`). A `truth_kwargs['manual_bias']` name is
    mapped through this module's historical `manual_bias` shapes.

    Returns
    -------
    (EnsembleEstimator, Observations, dict)
        Filtered ensemble, truth, and the error metrics.
    """
    truth_kwargs = dict(kwargs.pop('truth_kwargs', None) or {})
    if isinstance(truth_kwargs.get('manual_bias'), str):
        truth_kwargs['manual_bias'] = manual_bias(truth_kwargs['manual_bias'])
    return physical.run_experiment(CFG, truth_kwargs=truth_kwargs, **kwargs)


# --------------------------------------- Main ---------------------------------------- #

if __name__ == '__main__':

    args = parse_main_args(description=__doc__)

    filter_ens, truth, metrics = run_experiment()
    print_metrics(metrics, header='Lorenz63 twin experiment')

    filter_ens.visualize_history(truth=truth,
                                 plot_members=True,
                                 reference_t=Lorenz63.t_lyap,
                                 reference_a=truth.true_parameters)
    show_or_save_figs(args.save_figs, prefix='lorenz63')
